language: node_js
node_js:
- 0.1
- 0.11
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler
- bundle install
- npm install -g gulp
script:
- gulp deploy
env:
  global:
  - secure: kv//Ku13hAwOkA2tzx7Sd9QAPKRpnxixS5RbiWltqKhUJId3smITpiOZ5Nbx/89NKiYR8v8wAN2GmXk7Dist4kViksSqtJOncUSP0jOsEG4pFSg1yhCx8tli2UWKbO36TXNUvgc/TST/s702dc3zYmBTTf/AkP6dNK/rtYXcbt8=
  - secure: kkG+bsCHN466AJHqtBarEPwT7LgERoyjLWS+Tqpl5LgedISnu4cog0Oe5lZHGSYsK5sK3cZOhysviOf5xy7oOew7CLXZ8CsJOWk0EVJEmLh5zVDo5CMEZkVJbjHgvU/mwA5xCkwawQVpdxJLmx2a0oNTqFLEo2iRL0y8427BSrw=
