language: ruby
sudo: false
rvm:
- 2.0.0
branches:
  only:
  - master
bundler_args: "--without development --path=~/.bundle"
before_install:
- nvm install 0.11
- nvm use 0.11
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler
- bundle install
- npm install
- npm install bower
- bower install
script:
- gulp publish
after_success:
- gulp deploy
- gulp invalidate

