source 'https://rubygems.org'
gem 'jekyll'
gem 'fastimage'
gem 'nokogiri'
gem 'htmlentities'
gem 'babosa'
gem 's3_website'
gem 'chronic_duration', :git => 'https://github.com/gagarych/chronic_duration'
gem 'html_truncator'
gem 'jekyll-contentblocks'
gem 'russian'
